### ISSUE TITLE
Device not found error

### ISSUE THREAD

**Issue by michaelblight** [homeassistant-addons-eliseo/Resting-Catt#5]
I can use catt from the command line when installed on Linux, but with resting catt I am getting "Device not found" when I use the device name from Google Home. If I instead use the IP address of the device, it works, but returns an HTTP 500 code. However, I then cannot log in with a trusted network, despite having the IP of the device in "trusted_networks". I have to instead use `http://my_ha_ip:8123/lovelace-cast/clock`.
```
msg.headers = {};
msg.headers['content-type'] = 'application/json';

msg.payload = {
    "device": "192.168.0.123",
    "url": "https://mysubdomain.duckdns.org/lovelace-cast/clock"
}
```
And getting this in the log:
```
Starting Resting Catt
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:9898/ (Press CTRL+C to quit)
ERROR:app:Exception on /cast_site [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2096, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
192.168.0.62 - - [03/Jul/2022 12:18:20] "POST /cast_site HTTP/1.1" 500 -
INFO:werkzeug:192.168.0.62 - - [03/Jul/2022 12:18:20] "POST /cast_site HTTP/1.1" 500 -
```

**Comment by Happyrobot33** [comment]
Running into this on 2023.7 now and can't find a working workaround anymore
